# Site
name: 'Defy Finance'
description: 'Crypto Blog and Solidity Auditing Service'
logo: 'assets/images/DF.jpg'
favicon: 'assets/images/DF.jpg'
baseurl: ''
disqus: 'demowebsite'
email: ''
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Peter Todds
      site:           https://www.wowthemes.net
      avatar:         {{ site.baseurl }}/assets/images/defyfinancecofounder2.png
      bio:            "Hi, I am Peter, the co-founder of Defy Finance and Lead Solidity Auditor"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Susan Kane
      site:           https://www.wowthemes.net
      avatar:         {{ site.baseurl }}/assets/images/defyfinancecofounder.png
      bio:            "Blogger, Crypto Evangelist, love to meet new people and chat about Solidity!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Peter
      avatar: /assets/images/defyfinancecofounder2.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
